version: "3.9"
services:
  portfolio_postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
  portfolio:
    build:
      context: .
    environment:
      - ENV=PRODUCTION_TEST
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@portfolio_postgresql:5432/${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_SLUG=${ADMIN_SLUG}
    volumes:
      - media:/app/media/
      - static:/app/static/
      # develop volumes
      - portfolio_app:/app/portfolio/
      - home_app:/app/home/
      - templates:/app/templates/
      - project_app:/app/project/
    networks:
      - my_network
  portfolio-nginx:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - media:/usr/share/nginx/html/media/
      - static:/usr/share/nginx/html/static/
      - nginx_conf:/etc/nginx/conf.d/
      - nginx_log:/var/log/nginx/logs/
    networks:
      - my_network

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgresql_data/
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/media/
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/static/
  nginx_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx_conf/
  nginx_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/nginx-log/
  # develop volumes
  portfolio_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./portfolio/
  home_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./home/
  templates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./templates/
  project_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./project/

networks:
  my_network:
    driver: bridge

